package com.rs.epl.NB.oementity;
// Generated Feb 20, 2017 1:45:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

//import java.math.BigDecimal;
//import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;

/**
 * TtrnPolicy generated by hbm2java
 */
@Entity
@Table(name = "TTRN_POLICY_INFO")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="oem")
public class TtrnPolicy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;




	private String endorsementType;
	private String policyno;
	private String endorsementNo;

	
	
	private String productcode;
	private String accountcode;
	private String clientcode;
	private String branch;




	private String coverNoteNo;
	private String covernotedate;
	private Double incrementalsi;

	private String inceptiondate;
	private String expirydate;
	private String proposaldate;
	private String issuedate;
	private String effectivedate;
	private String accountdate;
	private String inceptiontime;
	private String expirytime;
	private String domicile;
	private String territory;
	private String bankCit;
	private String term;
	private String paymentmethod;

	private String underwritingyear;
	private String cbc;
	private String numtxt1;
	private String numtxt2;
	private String numtxt3;
	private String numberadditioninfo1;
	private String numberadditioninfo2;
	private String numberadditioninfo3;
	private String otherparty1;
	private String otherparty2;
	private String otherparty3;
	private String otherparty4;
	private String oragent;
	private String aaimembership;
	private String additionalinfo;
	private String zdilcm;
	private String zcld;
	private String zstax;
	private String zedcs;
	private String zcm;
	private String zcmtx;
	private String zovcm;
	private String zocmtx;
	private String zstdty;
	private String zsdexp;
	private String ZWROFF;
	private String cardnum;
	private String cardexp;
	private String chqNo;
	private String chqAmt;
	private String chqIssueDt;
	
	private String bankName;
	
	private String payTo;
	private String recieptNumber;
	
	private String receiptAmount;
	private String newclient;
	private String oldPolNum;
	private String bankCode;

	private int xgenProductid;
	private String cardType;
	private String cardIssuer;
	private String authNumber;

	private String settlementType;

	private String xgenEndorsementno;

	private String zovcmRate;
	private String webserviceStatus;
	private String requestTime;
	private String zkcess;

	private String bdMandateNo;
	private String bdCurrency;
	private String bdDepositBank;
	private String bdAccountName;
	private String bdMicrCode;
	private String bdIfscCode;
	private String bdTransactionNumber;

	private String bdAmount;
	private Date bankdebitReceivedDate;
	private String bdAccountNumber;

	private String RECEIPT_WEB_SERVICE;
	private String RECEIPT_REQUEST_TIME;
	private String ERRORDESC;
	private String MASTERUPDATE;
	
	@Column(name = "INVOICENUMBER")
	private String InvoiceNUmber;
	
//	@Column
//	private String PickupServer;
	
	@Column(name = "ZIGST")
	private String ZIGST;
	
	@Column(name = "ZCGST")
	private String ZCGST;
	
	@Column(name = "ZSGST")
	private String ZSGST;
	
	@Column(name = "ZUGST")
    private String ZUGST;

	public TtrnPolicy() {
	}



	@Column(name = "ENDORSEMENT_TYPE", length = 10)
	public String getEndorsementType() {
		return this.endorsementType;
	}

	public void setEndorsementType(String endorsementType) {
		this.endorsementType = endorsementType;
	}
     
	@Id
	@Column(name = "POLICYNO", length = 16)
	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	@Column(name = "ENDORSEMENT_NO", length = 3)
	public String getEndorsementNo() {
		return this.endorsementNo;
	}

	public void setEndorsementNo(String endorsementNo) {
		this.endorsementNo = endorsementNo;
	}

	

	@Column(name = "PRODUCTCODE", length = 10)
	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	@Column(name = "ACCOUNTCODE", length = 20)
	public String getAccountcode() {
		return this.accountcode;
	}

	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}

	@Column(name = "CLIENTCODE", length = 50)
	public String getClientcode() {
		return this.clientcode;
	}

	public void setClientcode(String clientcode) {
		this.clientcode = clientcode;
	}

	@Column(name = "BRANCH", length = 50)
	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	

	@Column(name = "COVER_NOTE_NO", length = 50)
	public String getCoverNoteNo() {
		return this.coverNoteNo;
	}

	public void setCoverNoteNo(String coverNoteNo) {
		this.coverNoteNo = coverNoteNo;
	}

//	@Temporal(TemporalType.DATE)
	@Column(name = "COVERNOTEDATE", length = 7)
	public String getCovernotedate() {
		return this.covernotedate;
	}

	public void setCovernotedate(String covernotedate) {
		this.covernotedate = covernotedate;
	}

	@Column(name = "INCREMENTALSI", precision = 12)
	public Double getIncrementalsi() {
		return this.incrementalsi;
	}

	public void setIncrementalsi(Double incrementalsi) {
		this.incrementalsi = incrementalsi;
	}

	

	@Column(name = "INCEPTIONDATE", length = 30)
	public String getInceptiondate() {
		return this.inceptiondate;
	}

	public void setInceptiondate(String inceptiondate) {
		this.inceptiondate = inceptiondate;
	}

	@Column(name = "EXPIRYDATE", length = 30)
	public String getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(String expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "PROPOSALDATE", length = 200)
	public String getProposaldate() {
		return this.proposaldate;
	}

	public void setProposaldate(String proposaldate) {
		this.proposaldate = proposaldate;
	}

	@Column(name = "ISSUEDATE", length = 30)
	public String getIssuedate() {
		return this.issuedate;
	}

	public void setIssuedate(String issuedate) {
		this.issuedate = issuedate;
	}

	@Column(name = "EFFECTIVEDATE", length = 30)
	public String getEffectivedate() {
		return this.effectivedate;
	}

	public void setEffectivedate(String effectivedate) {
		this.effectivedate = effectivedate;
	}

	@Column(name = "ACCOUNTDATE", length = 30)
	public String getAccountdate() {
		return this.accountdate;
	}

	public void setAccountdate(String accountdate) {
		this.accountdate = accountdate;
	}

	@Column(name = "INCEPTIONTIME", length = 100)
	public String getInceptiontime() {
		return this.inceptiontime;
	}

	public void setInceptiontime(String inceptiontime) {
		this.inceptiontime = inceptiontime;
	}

	@Column(name = "EXPIRYTIME", length = 100)
	public String getExpirytime() {
		return this.expirytime;
	}

	public void setExpirytime(String expirytime) {
		this.expirytime = expirytime;
	}
	@Column(name = "BANK_CIT", length = 400)
	public String getBankCit() {
		return this.bankCit;
	}
	
	public void setBankCit(String bankCit) {
		this.bankCit = bankCit;
	}

	@Column(name = "DOMICILE", length = 10)
	public String getDomicile() {
		return this.domicile;
	}

	public void setDomicile(String domicile) {
		this.domicile = domicile;
	}

	@Column(name = "TERRITORY", length = 100)
	public String getTerritory() {
		return this.territory;
	}

	public void setTerritory(String territory) {
		this.territory = territory;
	}

	

	@Column(name = "TERM", length = 10)
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Column(name = "PAYMENTMETHOD", length = 50)
	public String getPaymentmethod() {
		return this.paymentmethod;
	}

	public void setPaymentmethod(String paymentmethod) {
		this.paymentmethod = paymentmethod;
	}



	@Column(name = "UNDERWRITINGYEAR", precision = 22, scale = 0)
	public String getUnderwritingyear() {
		return this.underwritingyear;
	}

	public void setUnderwritingyear(String underwritingyear) {
		this.underwritingyear = underwritingyear;
	}

	@Column(name = "CBC", length = 200)
	public String getCbc() {
		return this.cbc;
	}

	public void setCbc(String cbc) {
		this.cbc = cbc;
	}

	@Column(name = "NUMTXT1", length = 200)
	public String getNumtxt1() {
		return this.numtxt1;
	}

	public void setNumtxt1(String numtxt1) {
		this.numtxt1 = numtxt1;
	}

	@Column(name = "NUMTXT2", length = 200)
	public String getNumtxt2() {
		return this.numtxt2;
	}

	public void setNumtxt2(String numtxt2) {
		this.numtxt2 = numtxt2;
	}

	@Column(name = "NUMTXT3", length = 200)
	public String getNumtxt3() {
		return this.numtxt3;
	}

	public void setNumtxt3(String numtxt3) {
		this.numtxt3 = numtxt3;
	}

	@Column(name = "NUMBERADDITIONINFO1", length = 200)
	public String getNumberadditioninfo1() {
		return this.numberadditioninfo1;
	}

	public void setNumberadditioninfo1(String numberadditioninfo1) {
		this.numberadditioninfo1 = numberadditioninfo1;
	}

	@Column(name = "NUMBERADDITIONINFO2", length = 50)
	public String getNumberadditioninfo2() {
		return this.numberadditioninfo2;
	}

	public void setNumberadditioninfo2(String numberadditioninfo2) {
		this.numberadditioninfo2 = numberadditioninfo2;
	}

	@Column(name = "NUMBERADDITIONINFO3", length = 50)
	public String getNumberadditioninfo3() {
		return this.numberadditioninfo3;
	}

	public void setNumberadditioninfo3(String numberadditioninfo3) {
		this.numberadditioninfo3 = numberadditioninfo3;
	}

	@Column(name = "OTHERPARTY1", length = 20)
	public String getOtherparty1() {
		return this.otherparty1;
	}

	public void setOtherparty1(String otherparty1) {
		this.otherparty1 = otherparty1;
	}

	@Column(name = "OTHERPARTY2", length = 20)
	public String getOtherparty2() {
		return this.otherparty2;
	}

	public void setOtherparty2(String otherparty2) {
		this.otherparty2 = otherparty2;
	}

	@Column(name = "OTHERPARTY3", length = 20)
	public String getOtherparty3() {
		return this.otherparty3;
	}

	public void setOtherparty3(String otherparty3) {
		this.otherparty3 = otherparty3;
	}

	@Column(name = "OTHERPARTY4", length = 20)
	public String getOtherparty4() {
		return this.otherparty4;
	}

	public void setOtherparty4(String otherparty4) {
		this.otherparty4 = otherparty4;
	}

	@Column(name = "ORAGENT", length = 30)
	public String getOragent() {
		return this.oragent;
	}

	public void setOragent(String oragent) {
		this.oragent = oragent;
	}

	@Column(name = "AAIMEMBERSHIP", length = 200)
	public String getAaimembership() {
		return this.aaimembership;
	}

	public void setAaimembership(String aaimembership) {
		this.aaimembership = aaimembership;
	}

	@Column(name = "ADDITIONALINFO", length = 200)
	public String getAdditionalinfo() {
		return this.additionalinfo;
	}

	public void setAdditionalinfo(String additionalinfo) {
		this.additionalinfo = additionalinfo;
	}

	@Column(name = "ZDILCM", length = 200)
	public String getZdilcm() {
		return this.zdilcm;
	}

	public void setZdilcm(String zdilcm) {
		this.zdilcm = zdilcm;
	}

	@Column(name = "ZCLD", length = 200)
	public String getZcld() {
		return this.zcld;
	}

	public void setZcld(String zcld) {
		this.zcld = zcld;
	}

	@Column(name = "ZSTAX", precision = 22, scale = 0)
	public String getZstax() {
		return this.zstax;
	}

	public void setZstax(String zstax) {
		this.zstax = zstax;
	}

	@Column(name = "ZEDCS", precision = 22, scale = 0)
	public String getZedcs() {
		return this.zedcs;
	}

	public void setZedcs(String zedcs) {
		this.zedcs = zedcs;
	}

	@Column(name = "ZCM", length = 200)
	public String getZcm() {
		return this.zcm;
	}

	public void setZcm(String zcm) {
		this.zcm = zcm;
	}

	@Column(name = "ZCMTX", length = 200)
	public String getZcmtx() {
		return this.zcmtx;
	}

	public void setZcmtx(String zcmtx) {
		this.zcmtx = zcmtx;
	}

	@Column(name = "ZOVCM", precision = 22, scale = 0)
	public String getZovcm() {
		return this.zovcm;
	}

	public void setZovcm(String zovcm) {
		this.zovcm = zovcm;
	}

	@Column(name = "ZOCMTX", length = 200)
	public String getZocmtx() {
		return this.zocmtx;
	}

	public void setZocmtx(String zocmtx) {
		this.zocmtx = zocmtx;
	}

	@Column(name = "ZSTDTY", precision = 22, scale = 0)
	public String getZstdty() {
		return this.zstdty;
	}

	public void setZstdty(String zstdty) {
		this.zstdty = zstdty;
	}

	@Column(name = "ZSDEXP", precision = 22, scale = 0)
	public String getZsdexp() {
		return this.zsdexp;
	}

	public void setZsdexp(String zsdexp) {
		this.zsdexp = zsdexp;
	}

	@Column(name = "ZWROFF")
	public String getZwroff() {
		return this.ZWROFF;
	}

	public void setZwroff(String zwroff) {
		this.ZWROFF = zwroff;
	}

	@Column(name = "CARDNUM", precision = 30, scale = 0)
	public String getCardnum() {
		return this.cardnum;
	}

	public void setCardnum(String cardnum) {
		this.cardnum = cardnum;
	}

	@Column(name = "CARDEXP", length = 50)
	public String getCardexp() {
		return this.cardexp;
	}

	public void setCardexp(String cardexp) {
		this.cardexp = cardexp;
	}

	@Column(name = "CHQ_NO", length = 23)
	public String getChqNo() {
		return this.chqNo;
	}

	public void setChqNo(String chqNo) {
		this.chqNo = chqNo;
	}

	@Column(name = "CHQ_AMT", precision = 12, scale = 0)
	public String getChqAmt() {
		return this.chqAmt;
	}

	public void setChqAmt(String chqAmt) {
		this.chqAmt = chqAmt;
	}

	@Column(name = "CHQ_ISSUE_DT", length = 30)
	public String getChqIssueDt() {
		return this.chqIssueDt;
	}

	public void setChqIssueDt(String chqIssueDt) {
		this.chqIssueDt = chqIssueDt;
	}

	

	@Column(name = "BANK_NAME", length = 300)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	

	@Column(name = "PAY_TO", length = 50)
	public String getPayTo() {
		return this.payTo;
	}

	public void setPayTo(String payTo) {
		this.payTo = payTo;
	}

	@Column(name = "RECIEPT_NUMBER", length = 10)
	public String getRecieptNumber() {
		return this.recieptNumber;
	}

	public void setRecieptNumber(String recieptNumber) {
		this.recieptNumber = recieptNumber;
	}

	

	@Column(name = "RECEIPT_AMOUNT", precision = 22, scale = 0)
	public String getReceiptAmount() {
		return this.receiptAmount;
	}

	public void setReceiptAmount(String receiptAmount) {
		this.receiptAmount = receiptAmount;
	}

	@Column(name = "NEWCLIENT", length = 1)
	public String getNewclient() {
		return this.newclient;
	}

	public void setNewclient(String newclient) {
		this.newclient = newclient;
	}

	@Column(name = "OLD_POL_NUM", length = 100)
	public String getOldPolNum() {
		return this.oldPolNum;
	}

	public void setOldPolNum(String oldPolNum) {
		this.oldPolNum = oldPolNum;
	}

	@Column(name = "BANK_CODE", length = 200)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	

	@Column(name = "XGEN_PRODUCTID", precision = 10, scale = 0)
	public int getXgenProductid() {
		return this.xgenProductid;
	}

	public void setXgenProductid(int xgenProductid) {
		this.xgenProductid = xgenProductid;
	}

	@Column(name = "CARD_TYPE", length = 50)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "CARD_ISSUER", length = 50)
	public String getCardIssuer() {
		return this.cardIssuer;
	}

	public void setCardIssuer(String cardIssuer) {
		this.cardIssuer = cardIssuer;
	}

	@Column(name = "AUTH_NUMBER", length = 50)
	public String getAuthNumber() {
		return this.authNumber;
	}

	public void setAuthNumber(String authNumber) {
		this.authNumber = authNumber;
	}



	@Column(name = "SETTLEMENT_TYPE", length = 50)
	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	

	@Column(name = "XGEN_ENDORSEMENTNO", length = 10)
	public String getXgenEndorsementno() {
		return this.xgenEndorsementno;
	}

	public void setXgenEndorsementno(String xgenEndorsementno) {
		this.xgenEndorsementno = xgenEndorsementno;
	}

	

	@Column(name = "ZOVCM_RATE", precision = 10)
	public String getZovcmRate() {
		return this.zovcmRate;
	}

	public void setZovcmRate(String zovcmRate) {
		this.zovcmRate = zovcmRate;
	}

	@Column(name = "WEBSERVICE_STATUS", length = 100)
	public String getWebserviceStatus() {
		return this.webserviceStatus;
	}

	public void setWebserviceStatus(String webserviceStatus) {
		this.webserviceStatus = webserviceStatus;
	}

	@Column(name = "REQUEST_TIME", length = 50)
	public String getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(String requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "ZKCESS", precision = 10)
	public String getZkcess() {
		return this.zkcess;
	}

	public void setZkcess(String zkcess) {
		this.zkcess = zkcess;
	}



	@Column(name = "BD_MANDATE_NO", length = 200)
	public String getBdMandateNo() {
		return this.bdMandateNo;
	}

	public void setBdMandateNo(String bdMandateNo) {
		this.bdMandateNo = bdMandateNo;
	}

	@Column(name = "BD_CURRENCY", length = 200)
	public String getBdCurrency() {
		return this.bdCurrency;
	}

	public void setBdCurrency(String bdCurrency) {
		this.bdCurrency = bdCurrency;
	}

	@Column(name = "BD_DEPOSIT_BANK", length = 400)
	public String getBdDepositBank() {
		return this.bdDepositBank;
	}

	public void setBdDepositBank(String bdDepositBank) {
		this.bdDepositBank = bdDepositBank;
	}

	@Column(name = "BD_ACCOUNT_NAME", length = 200)
	public String getBdAccountName() {
		return this.bdAccountName;
	}

	public void setBdAccountName(String bdAccountName) {
		this.bdAccountName = bdAccountName;
	}

	@Column(name = "BD_MICR_CODE", length = 200)
	public String getBdMicrCode() {
		return this.bdMicrCode;
	}

	public void setBdMicrCode(String bdMicrCode) {
		this.bdMicrCode = bdMicrCode;
	}

	@Column(name = "BD_IFSC_CODE", length = 200)
	public String getBdIfscCode() {
		return this.bdIfscCode;
	}

	public void setBdIfscCode(String bdIfscCode) {
		this.bdIfscCode = bdIfscCode;
	}

	@Column(name = "BD_TRANSACTION_NUMBER", length = 200)
	public String getBdTransactionNumber() {
		return this.bdTransactionNumber;
	}

	public void setBdTransactionNumber(String bdTransactionNumber) {
		this.bdTransactionNumber = bdTransactionNumber;
	}

	

	@Column(name = "BD_AMOUNT", precision = 22, scale = 0)
	public String getBdAmount() {
		return this.bdAmount;
	}

	public void setBdAmount(String bdAmount) {
		this.bdAmount = bdAmount;
	}

//	@Temporal(TemporalType.DATE)
	@Column(name = "BANKDEBIT_RECEIVED_DATE" /*, length = 7*/)
	public Date getBankdebitReceivedDate() {
		return this.bankdebitReceivedDate;
	}

	public void setBankdebitReceivedDate(Date bankdebitReceivedDate) {
		this.bankdebitReceivedDate = bankdebitReceivedDate;
	}

	@Column(name = "BD_ACCOUNT_NUMBER", length = 400)
	public String getBdAccountNumber() {
		return this.bdAccountNumber;
	}

	public void setBdAccountNumber(String bdAccountNumber) {
		this.bdAccountNumber = bdAccountNumber;
	}

	
	
	@Column(name = "RECEIPT_WEB_SERVICE")
	public String getRECEIPT_WEB_SERVICE() {
		return RECEIPT_WEB_SERVICE;
	}

	public void setRECEIPT_WEB_SERVICE(String rECEIPT_WEB_SERVICE) {
		RECEIPT_WEB_SERVICE = rECEIPT_WEB_SERVICE;
	}
    
	@Column(name = "RECEIPT_REQUEST_TIME")
 	public String getRECEIPT_REQUEST_TIME() {
		return RECEIPT_REQUEST_TIME;
	}

	public void setRECEIPT_REQUEST_TIME(String rECEIPT_REQUEST_TIME) {
		RECEIPT_REQUEST_TIME = rECEIPT_REQUEST_TIME;
	}

	@Column(name="ERRORDESC")
	public String getERRORDESC() {
		return ERRORDESC;
	}

	public void setERRORDESC(String eRRORDESC) {
		ERRORDESC = eRRORDESC;
	}
	
	@Column(name="MASTERUPDATE")
	public String getMASTERUPDATE() {
		return MASTERUPDATE;
	}

	public void setMASTERUPDATE(String mASTERUPDATE) {
		MASTERUPDATE = mASTERUPDATE;
	}
	

	public String getZIGST() {
		return ZIGST;
	}

	public void setZIGST(String zIGST) {
		ZIGST = zIGST;
	}

	public String getZCGST() {
		return ZCGST;
	}

	public void setZCGST(String zCGST) {
		ZCGST = zCGST;
	}

	public String getZSGST() {
		return ZSGST;
	}

	public void setZSGST(String zSGST) {
		ZSGST = zSGST;
	}
	
	public String getZUGST() {
		return ZUGST;
	}

	public void setZUGST(String zUGST) {
		ZUGST = zUGST;
	}
	
//	public String getPickupServer() {
//		return PickupServer;
//	}
//
//	public void setPickupServer(String pickupServer) {
//		PickupServer = pickupServer;
//	}
	
	
	public String getInvoiceNUmber() {
		return InvoiceNUmber;
	}

	public void setInvoiceNUmber(String invoiceNUmber) {
		InvoiceNUmber = invoiceNUmber;
	}
	
	
}













































//private String xgenPolicyno;
//private String generationmethod;	
//	private Boolean recordType;
//private Boolean recordNo;
//private String seriesGenerate;
//private String renewalno;
//	private String categorycode;
//		private String ocMpNo;
//			private String planno;
//			
//	private String declarationno;
//		
//			private Integer noofitems;
//			
//				private String sicurrency;
//private String premcurrency;
//
//	private String installmentmode;
//	private String bankAcNo;

//	private String autoSettlementFlag;
//	
//		private String businessType;
//private String numtxt4;
//private String numtxt5;
//private Long batchid;
//private Character active;
//	private String newAgent;
//		private String clientUpdate;
//			private Long recordno;
//private String numtext4;
//	private String blank;
//		private String bdCharges;
//		
//			private String pspname;
//private String aadhaarcardnumber;
//private String psppannumber;
//
//
//	public TtrnPolicy(String xgenPolicyno) {
//	this.xgenPolicyno = xgenPolicyno;
//}
//
//
//@Column(name = "XGEN_POLICYNO", unique = true, nullable = false, length = 16)
//public String getXgenPolicyno() {
//	return this.xgenPolicyno;
//}
//
//public void setXgenPolicyno(String xgenPolicyno) {
//	this.xgenPolicyno = xgenPolicyno;
//}
//
//@Column(name = "RECORD_TYPE", precision = 1, scale = 0)
//public Boolean getRecordType() {
//	return this.recordType;
//}
//
//public void setRecordType(Boolean recordType) {
//	this.recordType = recordType;
//}
//
//@Column(name = "RECORD_NO", precision = 1, scale = 0)
//public Boolean getRecordNo() {
//	return this.recordNo;
//}
//
//public void setRecordNo(Boolean recordNo) {
//	this.recordNo = recordNo;
//}
//
//@Column(name = "GENERATIONMETHOD", length = 1)
//public String getGenerationmethod() {
//	return this.generationmethod;
//}
//
//public void setGenerationmethod(String generationmethod) {
//	this.generationmethod = generationmethod;
//}
//
//@Column(name = "SERIES_GENERATE", length = 200)
//public String getSeriesGenerate() {
//	return this.seriesGenerate;
//}
//
//public void setSeriesGenerate(String seriesGenerate) {
//	this.seriesGenerate = seriesGenerate;
//}
//
//@Column(name = "RENEWALNO", length = 200)
//public String getRenewalno() {
//	return this.renewalno;
//}
//
//public void setRenewalno(String renewalno) {
//	this.renewalno = renewalno;
//}
//
//
//@Column(name = "CATEGORYCODE", length = 1)
//public String getCategorycode() {
//	return this.categorycode;
//}
//
//public void setCategorycode(String categorycode) {
//	this.categorycode = categorycode;
//}
//
//@Column(name = "OC_MP_NO", length = 200)
//public String getOcMpNo() {
//	return this.ocMpNo;
//}
//
//public void setOcMpNo(String ocMpNo) {
//	this.ocMpNo = ocMpNo;
//}
//
//@Column(name = "PLANNO", length = 200)
//public String getPlanno() {
//	return this.planno;
//}
//
//public void setPlanno(String planno) {
//	this.planno = planno;
//}
//
//@Column(name = "DECLARATIONNO", length = 200)
//public String getDeclarationno() {
//	return this.declarationno;
//}
//
//public void setDeclarationno(String declarationno) {
//	this.declarationno = declarationno;
//}
//
//@Column(name = "NOOFITEMS", precision = 5, scale = 0)
//public Integer getNoofitems() {
//	return this.noofitems;
//}
//
//public void setNoofitems(Integer noofitems) {
//	this.noofitems = noofitems;
//}
//
//@Column(name = "SICURRENCY", length = 3)
//public String getSicurrency() {
//	return this.sicurrency;
//}
//
//public void setSicurrency(String sicurrency) {
//	this.sicurrency = sicurrency;
//}
//
//@Column(name = "PREMCURRENCY", length = 3)
//public String getPremcurrency() {
//	return this.premcurrency;
//}
//
//public void setPremcurrency(String premcurrency) {
//	this.premcurrency = premcurrency;
//}
//
//	@Column(name = "INSTALLMENTMODE", length = 50)
//public String getInstallmentmode() {
//	return this.installmentmode;
//}
//
//public void setInstallmentmode(String installmentmode) {
//	this.installmentmode = installmentmode;
//}
//
//@Column(name = "BANK_AC_NO", length = 200)
//public String getBankAcNo() {
//	return this.bankAcNo;
//}
//
//public void setBankAcNo(String bankAcNo) {
//	this.bankAcNo = bankAcNo;
//}
//

//
//@Column(name = "AUTO_SETTLEMENT_FLAG", length = 1)
//public String getAutoSettlementFlag() {
//	return this.autoSettlementFlag;
//}
//
//public void setAutoSettlementFlag(String autoSettlementFlag) {
//	this.autoSettlementFlag = autoSettlementFlag;
//}
//
//@Column(name = "BUSINESS_TYPE", length = 3)
//public String getBusinessType() {
//	return this.businessType;
//}
//
//public void setBusinessType(String businessType) {
//	this.businessType = businessType;
//}
//
//@Column(name = "NUMTXT4", length = 200)
//public String getNumtxt4() {
//	return this.numtxt4;
//}
//
//public void setNumtxt4(String numtxt4) {
//	this.numtxt4 = numtxt4;
//}
//
//@Column(name = "NUMTXT5", length = 200)
//public String getNumtxt5() {
//	return this.numtxt5;
//}
//
//public void setNumtxt5(String numtxt5) {
//	this.numtxt5 = numtxt5;
//}
//
//@Column(name = "BATCHID", precision = 10, scale = 0)
//public Long getBatchid() {
//	return this.batchid;
//}
//
//public void setBatchid(Long batchid) {
//	this.batchid = batchid;
//}
//
//@Column(name = "ACTIVE", length = 1)
//public Character getActive() {
//	return this.active;
//}
//
//public void setActive(Character active) {
//	this.active = active;
//}
//
//	@Column(name = "NEW_AGENT", length = 50)
//public String getNewAgent() {
//	return this.newAgent;
//}
//
//public void setNewAgent(String newAgent) {
//	this.newAgent = newAgent;
//}
//
//@Column(name = "CLIENT_UPDATE", length = 50)
//public String getClientUpdate() {
//	return this.clientUpdate;
//}
//
//public void setClientUpdate(String clientUpdate) {
//	this.clientUpdate = clientUpdate;
//}
//
//@Column(name = "RECORDNO", precision = 10, scale = 0)
//public Long getRecordno() {
//	return this.recordno;
//}
//
//public void setRecordno(Long recordno) {
//	this.recordno = recordno;
//}
//
//@Column(name = "NUMTEXT4", length = 100)
//public String getNumtext4() {
//	return this.numtext4;
//}
//
//public void setNumtext4(String numtext4) {
//	this.numtext4 = numtext4;
//}
//
//	@Column(name = "BLANK", length = 200)
//public String getBlank() {
//	return this.blank;
//}
//
//public void setBlank(String blank) {
//	this.blank = blank;
//}
//
//@Column(name = "BD_CHARGES", length = 200)
//public String getBdCharges() {
//	return this.bdCharges;
//}
//
//public void setBdCharges(String bdCharges) {
//	this.bdCharges = bdCharges;
//}
//
//@Column(name = "PSPNAME", length = 400)
//public String getPspname() {
//	return this.pspname;
//}
//
//public void setPspname(String pspname) {
//	this.pspname = pspname;
//}
//
//@Column(name = "AADHAARCARDNUMBER", length = 400)
//public String getAadhaarcardnumber() {
//	return this.aadhaarcardnumber;
//}
//
//public void setAadhaarcardnumber(String aadhaarcardnumber) {
//	this.aadhaarcardnumber = aadhaarcardnumber;
//}
//
//@Column(name = "PSPPANNUMBER", length = 400)
//public String getPsppannumber() {
//	return this.psppannumber;
//}
//
//public void setPsppannumber(String psppannumber) {
//	this.psppannumber = psppannumber;
//}
