package com.fa.component.policy;
// Generated Feb 17, 2017 1:17:05 PM by Hibernate Tools 4.3.5.Final

//import java.io.Serializable;

//import java.math.BigDecimal;
//import java.util.HashSet;
//import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
//import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
//import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
//import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
//import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

//import com.sun.java.util.jar.pack.Package.Class.Field;

/**
 * Iicoverage generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="employee")
@Table(name = "IICOVERAGE")
@Access(AccessType.PROPERTY)
public class Iicoverage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

/*	@GenericGenerator(name = "custom_Iicoverage", strategy = "native")
	@GeneratedValue(generator = "custom_Iicoverage")*/
//   @Access(AccessType.FIELD)
//  @GenericGenerator(name = "custom_policy", strategy = "sequence" , parameters = {
//	            @org.hibernate.annotations.Parameter(name = "sequenceName", value = "sequence"),
//	            @org.hibernate.annotations.Parameter(name = "allocationSize", value = "1"),
//	    })
//  @GeneratedValue(generator = "custom_policy", strategy=GenerationType.SEQUENCE)	
//	@GenericGenerator(name = "ItemCoverage", strategy = "increment")
//	@GeneratedValue(generator = "ItemCoverage") 
   
	@Id
    @Access(AccessType.FIELD)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "partner_sequence")
	@SequenceGenerator(initialValue=1, allocationSize=1,name = "partner_sequence",sequenceName="ITEMCOV_SEQ")
	@Column(name = "IICOVERAGEID")
	private Long iicoverageid;
//	private Policyitem policyitem;
	private String code;
//	private String name;
//	private String displayname;
	private String premium;
	private String suminsuredname;
	private String suminsuredamount;
	private String deductiblename;
	private String deductibleamount;
//	private String addlsuminsuredname;
//	private Double addlsuminsuredamount;
//	private String addldeductiblename;
//	private Double addldeductibleamount;
//	private Double endorsementpremium;
//	private Date effectivedate;
//	private Date expirydate;
//	private Boolean isexternal;
	
//	@Column(name = "GSTNNUMBER")
//	private String Gstnnumber;
	
/*	private Set<Iisubcoverage> iisubcoverages = new HashSet<Iisubcoverage>(0);
	private Set<Iicovelement> iicovelements = new HashSet<Iicovelement>(0);
	private Set<Iicovvariables> iicovvariableses = new HashSet<Iicovvariables>(0);*/

	public Iicoverage() {
	}

	public Iicoverage(Long iicoverageid) {
		this.iicoverageid = iicoverageid;
	}
	
	public Long getIicoverageid() {
		return this.iicoverageid;
	}

	public void setIicoverageid(Long iicoverageid) {
		this.iicoverageid = iicoverageid;
	}

/*	@ManyToOne(cascade=CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Policyitem getPolicyitem() {
		return this.policyitem;
	}

	public void setPolicyitem(Policyitem policyitem) {
		this.policyitem = policyitem;
	}*/

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

//	@Column(name = "NAME")
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "DISPLAYNAME")
//	public String getDisplayname() {
//		return this.displayname;
//	}
//
//	public void setDisplayname(String displayname) {
//		this.displayname = displayname;
//	}

	@Column(name = "PREMIUM", precision = 126, scale = 0)
	public String getPremium() {
		return this.premium;
	}

	public void setPremium(String premium) {
		this.premium = premium;
	}

	@Column(name = "SUMINSUREDNAME")
	public String getSuminsuredname() {
		return this.suminsuredname;
	}

	public void setSuminsuredname(String suminsuredname) {
		this.suminsuredname = suminsuredname;
	}
//
	@Column(name = "SUMINSUREDAMOUNT", precision = 126, scale = 0)
	public String getSuminsuredamount() {
		return this.suminsuredamount;
	}

	public void setSuminsuredamount(String suminsuredamount) {
		this.suminsuredamount = suminsuredamount;
	}

	@Column(name = "DEDUCTIBLENAME")
	public String getDeductiblename() {
		return this.deductiblename;
	}

	public void setDeductiblename(String deductiblename) {
		this.deductiblename = deductiblename;
	}

	@Column(name = "DEDUCTIBLEAMOUNT", precision = 126, scale = 0)
	public String getDeductibleamount() {
		return this.deductibleamount;
	}

	public void setDeductibleamount(String deductibleamount) {
		this.deductibleamount = deductibleamount;
	}

//	@Column(name = "ADDLSUMINSUREDNAME")
//	public String getAddlsuminsuredname() {
//		return this.addlsuminsuredname;
//	}
//
//	public void setAddlsuminsuredname(String addlsuminsuredname) {
//		this.addlsuminsuredname = addlsuminsuredname;
//	}
//
//	@Column(name = "ADDLSUMINSUREDAMOUNT", precision = 126, scale = 0)
//	public Double getAddlsuminsuredamount() {
//		return this.addlsuminsuredamount;
//	}
//
//	public void setAddlsuminsuredamount(Double addlsuminsuredamount) {
//		this.addlsuminsuredamount = addlsuminsuredamount;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLENAME")
//	public String getAddldeductiblename() {
//		return this.addldeductiblename;
//	}
//
//	public void setAddldeductiblename(String addldeductiblename) {
//		this.addldeductiblename = addldeductiblename;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLEAMOUNT", precision = 126, scale = 0)
//	public Double getAddldeductibleamount() {
//		return this.addldeductibleamount;
//	}
//
//	public void setAddldeductibleamount(Double addldeductibleamount) {
//		this.addldeductibleamount = addldeductibleamount;
//	}
//
//	@Column(name = "ENDORSEMENTPREMIUM", precision = 126, scale = 0)
//	public Double getEndorsementpremium() {
//		return this.endorsementpremium;
//	}
//
//	public void setEndorsementpremium(Double endorsementpremium) {
//		this.endorsementpremium = endorsementpremium;
//	}
//
//	@Column(name = "EFFECTIVEDATE")
//	public Date getEffectivedate() {
//		return this.effectivedate;
//	}
//
//	public void setEffectivedate(Date effectivedate) {
//		this.effectivedate = effectivedate;
//	}
//
//	@Column(name = "EXPIRYDATE")
//	public Date getExpirydate() {
//		return this.expirydate;
//	}
//
//	public void setExpirydate(Date expirydate) {
//		this.expirydate = expirydate;
//	}
//
//	@Column(name = "ISEXTERNAL", precision = 1, scale = 0)
//	public Boolean getIsexternal() {
//		return this.isexternal;
//	}
//
//	public void setIsexternal(Boolean isexternal) {
//		this.isexternal = isexternal;
//	}

	
	
//	public String getGstnnumber() {
//		return Gstnnumber;
//	}
//
//	public void setGstnnumber(String gstnnumber) {
//		Gstnnumber = gstnnumber;
//	}

//	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "iicoverage")
//	public Set<Iisubcoverage> getIisubcoverages() {
//		return this.iisubcoverages;
//	}
//
//	public void setIisubcoverages(Set<Iisubcoverage> iisubcoverages) {
//		this.iisubcoverages = iisubcoverages;
//	}
//
//	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "iicoverage")
//	public Set<Iicovelement> getIicovelements() {
//		return this.iicovelements;
//	}
//
//	public void setIicovelements(Set<Iicovelement> iicovelements) {
//		this.iicovelements = iicovelements;
//	}
//
//	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "iicoverage")
//	public Set<Iicovvariables> getIicovvariableses() {
//		return this.iicovvariableses;
//	}
//
//	public void setIicovvariableses(Set<Iicovvariables> iicovvariableses) {
//		this.iicovvariableses = iicovvariableses;
//	}

	
	
}
