package com.fa.component.policy;
//package com.rs.epl.NB.policyentity;
//// Generated Feb 17, 2017 1:17:05 PM by Hibernate Tools 4.3.5.Final
//
////import java.io.Serializable;
//import java.math.BigDecimal;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
////import javax.persistence.JoinColumn;
////import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
//import javax.persistence.SequenceGenerator;
//import javax.persistence.Table;
//
///**
// * Iisubcoverage generated by hbm2java
// */
//@Entity
//@Table(name = "IISUBCOVERAGE")
//public class Iisubcoverage implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 1L;
//	private BigDecimal iisubcovid;
///*	private Iicoverage iicoverage;*/
//	private String code;
//	private String name;
//	private String displayname;
//	private Double premium;
//	private String suminsuredname;
//	private Double suminsuredamount;
//	private String deductiblename;
//	private Double deductibleamount;
//	private String addlsuminsuredname;
//	private Double addlsuminsuredamount;
//	private String addldeductiblename;
//	private Double addldeductibleamount;
//	private Double endorsementpremium;
//	private Date effectivedate;
//	private Date expirydate;
//	private Boolean isexternal;
//	private Set<Iisubcovelement> iisubcovelements = new HashSet<Iisubcovelement>(0);
//	private Set<Iisubcovvariables> iisubcovvariableses = new HashSet<Iisubcovvariables>(0);
//
//	public Iisubcoverage() {
//	}
//
//	public Iisubcoverage(BigDecimal iisubcovid) {
//		this.iisubcovid = iisubcovid;
//	}
//
//	/*public Iisubcoverage(BigDecimal iisubcovid, Iicoverage iicoverage, String code, String name, String displayname,
//			Double premium, String suminsuredname, Double suminsuredamount, String deductiblename,
//			Double deductibleamount, String addlsuminsuredname, Double addlsuminsuredamount, String addldeductiblename,
//			Double addldeductibleamount, Double endorsementpremium, Date effectivedate, Date expirydate,
//			Boolean isexternal, Set<Iisubcovelement> iisubcovelements, Set<Iisubcovvariables> iisubcovvariableses) {
//		this.iisubcovid = iisubcovid;
//		this.iicoverage = iicoverage;
//		this.code = code;
//		this.name = name;
//		this.displayname = displayname;
//		this.premium = premium;
//		this.suminsuredname = suminsuredname;
//		this.suminsuredamount = suminsuredamount;
//		this.deductiblename = deductiblename;
//		this.deductibleamount = deductibleamount;
//		this.addlsuminsuredname = addlsuminsuredname;
//		this.addlsuminsuredamount = addlsuminsuredamount;
//		this.addldeductiblename = addldeductiblename;
//		this.addldeductibleamount = addldeductibleamount;
//		this.endorsementpremium = endorsementpremium;
//		this.effectivedate = effectivedate;
//		this.expirydate = expirydate;
//		this.isexternal = isexternal;
//		this.iisubcovelements = iisubcovelements;
//		this.iisubcovvariableses = iisubcovvariableses;
//	}*/
//
//	@Id
//    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "partner_sequence")
//	@SequenceGenerator(initialValue=1, allocationSize=1,name = "partner_sequence",sequenceName="partner_sequence5")
//	@Column(name = "IISUBCOVID", unique = true, nullable = false, scale = 0)
//	public BigDecimal getIisubcovid() {
//		return this.iisubcovid;
//	}
//
//	public void setIisubcovid(BigDecimal iisubcovid) {
//		this.iisubcovid = iisubcovid;
//	}
//
///*	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "IICOVERAGEID")
//	public Iicoverage getIicoverage() {
//		return this.iicoverage;
//	}
//
//	public void setIicoverage(Iicoverage iicoverage) {
//		this.iicoverage = iicoverage;
//	}*/
//
//	@Column(name = "CODE")
//	public String getCode() {
//		return this.code;
//	}
//
//	public void setCode(String code) {
//		this.code = code;
//	}
//
//	@Column(name = "NAME")
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "DISPLAYNAME")
//	public String getDisplayname() {
//		return this.displayname;
//	}
//
//	public void setDisplayname(String displayname) {
//		this.displayname = displayname;
//	}
//
//	@Column(name = "PREMIUM", precision = 126, scale = 0)
//	public Double getPremium() {
//		return this.premium;
//	}
//
//	public void setPremium(Double premium) {
//		this.premium = premium;
//	}
//
//	@Column(name = "SUMINSUREDNAME")
//	public String getSuminsuredname() {
//		return this.suminsuredname;
//	}
//
//	public void setSuminsuredname(String suminsuredname) {
//		this.suminsuredname = suminsuredname;
//	}
//
//	@Column(name = "SUMINSUREDAMOUNT", precision = 126, scale = 0)
//	public Double getSuminsuredamount() {
//		return this.suminsuredamount;
//	}
//
//	public void setSuminsuredamount(Double suminsuredamount) {
//		this.suminsuredamount = suminsuredamount;
//	}
//
//	@Column(name = "DEDUCTIBLENAME")
//	public String getDeductiblename() {
//		return this.deductiblename;
//	}
//
//	public void setDeductiblename(String deductiblename) {
//		this.deductiblename = deductiblename;
//	}
//
//	@Column(name = "DEDUCTIBLEAMOUNT", precision = 126, scale = 0)
//	public Double getDeductibleamount() {
//		return this.deductibleamount;
//	}
//
//	public void setDeductibleamount(Double deductibleamount) {
//		this.deductibleamount = deductibleamount;
//	}
//
//	@Column(name = "ADDLSUMINSUREDNAME")
//	public String getAddlsuminsuredname() {
//		return this.addlsuminsuredname;
//	}
//
//	public void setAddlsuminsuredname(String addlsuminsuredname) {
//		this.addlsuminsuredname = addlsuminsuredname;
//	}
//
//	@Column(name = "ADDLSUMINSUREDAMOUNT", precision = 126, scale = 0)
//	public Double getAddlsuminsuredamount() {
//		return this.addlsuminsuredamount;
//	}
//
//	public void setAddlsuminsuredamount(Double addlsuminsuredamount) {
//		this.addlsuminsuredamount = addlsuminsuredamount;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLENAME")
//	public String getAddldeductiblename() {
//		return this.addldeductiblename;
//	}
//
//	public void setAddldeductiblename(String addldeductiblename) {
//		this.addldeductiblename = addldeductiblename;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLEAMOUNT", precision = 126, scale = 0)
//	public Double getAddldeductibleamount() {
//		return this.addldeductibleamount;
//	}
//
//	public void setAddldeductibleamount(Double addldeductibleamount) {
//		this.addldeductibleamount = addldeductibleamount;
//	}
//
//	@Column(name = "ENDORSEMENTPREMIUM", precision = 126, scale = 0)
//	public Double getEndorsementpremium() {
//		return this.endorsementpremium;
//	}
//
//	public void setEndorsementpremium(Double endorsementpremium) {
//		this.endorsementpremium = endorsementpremium;
//	}
//
//	@Column(name = "EFFECTIVEDATE")
//	public Date getEffectivedate() {
//		return this.effectivedate;
//	}
//
//	public void setEffectivedate(Date effectivedate) {
//		this.effectivedate = effectivedate;
//	}
//
//	@Column(name = "EXPIRYDATE")
//	public Date getExpirydate() {
//		return this.expirydate;
//	}
//
//	public void setExpirydate(Date expirydate) {
//		this.expirydate = expirydate;
//	}
//
//	@Column(name = "ISEXTERNAL", precision = 1, scale = 0)
//	public Boolean getIsexternal() {
//		return this.isexternal;
//	}
//
//	public void setIsexternal(Boolean isexternal) {
//		this.isexternal = isexternal;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iisubcoverage")
//	public Set<Iisubcovelement> getIisubcovelements() {
//		return this.iisubcovelements;
//	}
//
//	public void setIisubcovelements(Set<Iisubcovelement> iisubcovelements) {
//		this.iisubcovelements = iisubcovelements;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iisubcoverage")
//	public Set<Iisubcovvariables> getIisubcovvariableses() {
//		return this.iisubcovvariableses;
//	}
//
//	public void setIisubcovvariableses(Set<Iisubcovvariables> iisubcovvariableses) {
//		this.iisubcovvariableses = iisubcovvariableses;
//	}
//
//}
