package com.fa.component.policy;
// Generated Feb 17, 2017 1:17:05 PM by Hibernate Tools 4.3.5.Final

//import java.io.Serializable;
//import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Access;
import javax.persistence.AccessType;
//import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
//import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT")
@Access(AccessType.PROPERTY)
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="employee")
public class Payment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

/*	@GenericGenerator(name = "custom_Payment", strategy = "native")
	@GeneratedValue(generator = "custom_Payment")*/
	
//    @GenericGenerator(name = "Payment", strategy = "increment")
//	@GeneratedValue(generator = "Payment")  	
//	@Id
//	@Access(AccessType.FIELD)
//    @GenericGenerator(name = "custom_policy", strategy = "sequence" , parameters = {
//            @org.hibernate.annotations.Parameter(name = "sequenceName", value = "sequence"),
//            @org.hibernate.annotations.Parameter(name = "allocationSize", value = "1"),
//    })
//	@GeneratedValue(generator = "custom_policy", strategy=GenerationType.SEQUENCE)	
	
	@Id
	@Access(AccessType.FIELD)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "partner_sequence")
	@SequenceGenerator(initialValue=1, allocationSize=1,name = "partner_sequence",sequenceName="PAYMENT_SEQ")
	@Column(name = "ID")
	private Long id;
//	private Policy policy;
	private String instrumenttype;
	private String instrumentexpdt;
	private String paymenttype;
	private String paymentdate;
	private String paymentamount;
	private String receiptnumber;
	private String instrumentnumber;
	private String instrumentbank;
	private String instrumentbranch;
	private Date instrumentdate;
//	private Boolean islocalinstrument;
	private String pgserviceprovider;
	private String payeename;
//	private Boolean iscustomerpayment;
	private String micrcode;
	private String ifsccode;
	private String depositingBankCode;
	@Column(name="receipt_amount")
	private String receipt_amount;
	@Column(name="CBC")
	private String CBC;
	@Column(name="BankCity")
	private String BankCity;
	@Column(name="payto")
	private String payto="RSAIC Limited";
	
	@Column(name="TRANSCATION_NO")
    private String TRANSCATION_NO;
	
	public Payment() {
	}

	public Payment(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

//	@ManyToOne(cascade=CascadeType.ALL,fetch = FetchType.LAZY)
//	@JoinColumn(name = "POLID")
//	public Policy getPolicy() {
//		return this.policy;
//	}
//
//	public void setPolicy(Policy policy) {
//		this.policy = policy;
//	}

	@Column(name = "INSTRUMENTTYPE")
	public String getInstrumenttype() {
		return this.instrumenttype;
	}
	@Column(name = "DepositingBankCode")
	public String getDepositingBankCode() {
		return depositingBankCode;
	}

	public void setDepositingBankCode(String depositingBankCode) {
		this.depositingBankCode = depositingBankCode;
	}

	public void setInstrumenttype(String instrumenttype) {
		this.instrumenttype = instrumenttype;
	}

	@Column(name = "INSTRUMENTEXPDT")
	public String getInstrumentexpdt() {
		return this.instrumentexpdt;
	}

	public void setInstrumentexpdt(String instrumentexpdt) {
		this.instrumentexpdt = instrumentexpdt;
	}

	@Column(name = "PAYMENTTYPE")
	public String getPaymenttype() {
		return this.paymenttype;
	}

	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	@Column(name = "PAYMENTDATE")
	public String getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(String paymentdate) {
		this.paymentdate = paymentdate;
	}

	@Column(name = "PAYMENTAMOUNT", precision = 126, scale = 0)
	public String getPaymentamount() {
		return this.paymentamount;
	}

	public void setPaymentamount(String paymentamount) {
		this.paymentamount = paymentamount;
	}

	@Column(name = "RECEIPTNUMBER")
	public String getReceiptnumber() {
		return this.receiptnumber;
	}

	public void setReceiptnumber(String receiptnumber) {
		this.receiptnumber = receiptnumber;
	}

	@Column(name = "INSTRUMENTNUMBER")
	public String getInstrumentnumber() {
		return this.instrumentnumber;
	}

	public void setInstrumentnumber(String instrumentnumber) {
		this.instrumentnumber = instrumentnumber;
	}

	@Column(name = "INSTRUMENTBANK")
	public String getInstrumentbank() {
		return this.instrumentbank;
	}

	public void setInstrumentbank(String instrumentbank) {
		this.instrumentbank = instrumentbank;
	}

	@Column(name = "INSTRUMENTBRANCH")
	public String getInstrumentbranch() {
		return this.instrumentbranch;
	}

	public void setInstrumentbranch(String instrumentbranch) {
		this.instrumentbranch = instrumentbranch;
	}

	@Column(name = "INSTRUMENTDATE")
	public Date getInstrumentdate() {
		return this.instrumentdate;
	}

	public void setInstrumentdate(Date instrumentdate) {
		this.instrumentdate = instrumentdate;
	}

//	@Column(name = "ISLOCALINSTRUMENT", precision = 1, scale = 0)
//	public Boolean getIslocalinstrument() {
//		return this.islocalinstrument;
//	}
//
//	public void setIslocalinstrument(Boolean islocalinstrument) {
//		this.islocalinstrument = islocalinstrument;
//	}

	@Column(name = "PGSERVICEPROVIDER")
	public String getPgserviceprovider() {
		return this.pgserviceprovider;
	}

	public void setPgserviceprovider(String pgserviceprovider) {
		this.pgserviceprovider = pgserviceprovider;
	}

	@Column(name = "PAYEENAME")
	public String getPayeename() {
		return this.payeename;
	}

	public void setPayeename(String payeename) {
		this.payeename = payeename;
	}

//	@Column(name = "ISCUSTOMERPAYMENT", precision = 1, scale = 0)
//	public Boolean getIscustomerpayment() {
//		return this.iscustomerpayment;
//	}
//
//	public void setIscustomerpayment(Boolean iscustomerpayment) {
//		this.iscustomerpayment = iscustomerpayment;
//	}

	@Column(name = "MICRCODE")
	public String getMicrcode() {
		return this.micrcode;
	}

	public void setMicrcode(String micrcode) {
		this.micrcode = micrcode;
	}

	@Column(name = "IFSCCODE")
	public String getIfsccode() {
		return this.ifsccode;
	}

	public void setIfsccode(String ifsccode) {
		this.ifsccode = ifsccode;
	}
	public String getCBC() {
		return CBC;
	}

	public void setCBC(String cBC) {
		CBC = cBC;
	}
	
	public String getBankCity() {
		return BankCity;
	}

	public void setBankCity(String bankCity) {
		BankCity = bankCity;
	}
	public String getReceipt_amount() {
		return receipt_amount;
	}

	public void setReceipt_amount(String receipt_amount) {
		this.receipt_amount = receipt_amount;
	}

	public String getPayto() {
		return payto;
	}

	public void setPayto(String payto) {
		this.payto = payto;
	}
	
	public String getTRANSCATION_NO() {
		return TRANSCATION_NO;
	}

	public void setTRANSCATION_NO(String tRANSCATION_NO) {
		TRANSCATION_NO = tRANSCATION_NO;
	}	
}
