package com.fa.component.policy;
// Generated Feb 17, 2017 1:17:05 PM by Hibernate Tools 4.3.5.Final

//import java.io.Serializable;
//import java.math.BigDecimal;
//import java.util.HashSet;
//import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
//import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
//import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
//import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
//import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/** 
 * Policycoverage generated by hbm2java
 */
@Entity
@Table(name = "POLICYCOVERAGE")
@Access(AccessType.PROPERTY)
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="employee")
public class Policycoverage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

//	@Access(AccessType.FIELD)
//	@GenericGenerator(name = "custom_policy", strategy = "sequence" , parameters = {
//			@org.hibernate.annotations.Parameter(name = "sequenceName", value = "sequence"),
//			@org.hibernate.annotations.Parameter(name = "allocationSize", value = "1"),
//	})
//	@GeneratedValue(generator = "custom_policy", strategy=GenerationType.SEQUENCE)
	
//	@GenericGenerator(name = "custom_PolicyCOverage", strategy = "increment")
//	@GeneratedValue(generator = "custom_PolicyCOverage")
	
	@Id
	@Access(AccessType.FIELD)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "partner_sequence")
	@SequenceGenerator(initialValue=1, allocationSize=1,name = "partner_sequence",sequenceName="POLCOV_SEQ")
	@Column(name = "POLCOVID")
	private Long polcovid;
//	private Policy policy;
	private String code;
	private String name;
//	private String displayname;
	private String premium;
//	private String suminsuredname;
//	private Double suminsuredamount;
//	private String deductiblename;
//	private Double deductibleamount;
//	private String addlsuminsuredname;
//	private Double addlsuminsuredamount;
//	private String addldeductiblename;
//	private Double addldeductibleamount;
//	private Double endorsementpremium;
//	private Date effectivedate;
//	private Date expirydate;
//	private Boolean isexternal;
/*	private Set<Policysubcoverage> policysubcoverages = new HashSet<Policysubcoverage>(0);
	private Set<Policycovelement> policycovelements = new HashSet<Policycovelement>(0);
	private Set<Policycovvariables> policycovvariableses = new HashSet<Policycovvariables>(0);*/

	public Policycoverage() {
	}

	public Policycoverage(Long polcovid) {
		this.polcovid = polcovid;
	}

	/*public Policycoverage(Long polcovid, Policy policy, String code, String name, String displayname,
			String premium, String suminsuredname, Double suminsuredamount, String deductiblename,
			Double deductibleamount, String addlsuminsuredname, Double addlsuminsuredamount, String addldeductiblename,
			Double addldeductibleamount, Double endorsementpremium, Date effectivedate, Date expirydate,
			Boolean isexternal, Set<Policysubcoverage> policysubcoverages, Set<Policycovelement> policycovelements,
			Set<Policycovvariables> policycovvariableses) {
		this.polcovid = polcovid;
		this.policy = policy;
		this.code = code;
		this.name = name;
		this.displayname = displayname;
		this.premium = premium;
		this.suminsuredname = suminsuredname;
		this.suminsuredamount = suminsuredamount;
		this.deductiblename = deductiblename;
		this.deductibleamount = deductibleamount;
		this.addlsuminsuredname = addlsuminsuredname;
		this.addlsuminsuredamount = addlsuminsuredamount;
		this.addldeductiblename = addldeductiblename;
		this.addldeductibleamount = addldeductibleamount;
		this.endorsementpremium = endorsementpremium;
		this.effectivedate = effectivedate;
		this.expirydate = expirydate;
		this.isexternal = isexternal;
		this.policysubcoverages = policysubcoverages;
		this.policycovelements = policycovelements;
		this.policycovvariableses = policycovvariableses;
	}
*/
	public Long getPolcovid() {
		return this.polcovid;
	}

	public void setPolcovid(Long polcovid) {
		this.polcovid = polcovid;
	}

/*	@ManyToOne(cascade=CascadeType.ALL,fetch = FetchType.LAZY)
	@JoinColumn(name = "POLID")
	public Policy getPolicy() {
		return this.policy;
	}

	public void setPolicy(Policy policy) {
		this.policy = policy;
	}*/

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
//
//	@Column(name = "DISPLAYNAME")
//	public String getDisplayname() {
//		return this.displayname;
//	}
//
//	public void setDisplayname(String displayname) {
//		this.displayname = displayname;
//	}

	@Column(name = "PREMIUM", precision = 126, scale = 0)
	public String getPremium() {
		return this.premium;
	}

	public void setPremium(String premium) {
		this.premium = premium;
	}

//	@Column(name = "SUMINSUREDNAME")
//	public String getSuminsuredname() {
//		return this.suminsuredname;
//	}
//
//	public void setSuminsuredname(String suminsuredname) {
//		this.suminsuredname = suminsuredname;
//	}

//	@Column(name = "SUMINSUREDAMOUNT", precision = 126, scale = 0)
//	public Double getSuminsuredamount() {
//		return this.suminsuredamount;
//	}
//
//	public void setSuminsuredamount(Double suminsuredamount) {
//		this.suminsuredamount = suminsuredamount;
//	}

//	@Column(name = "DEDUCTIBLENAME")
//	public String getDeductiblename() {
//		return this.deductiblename;
//	}
//
//	public void setDeductiblename(String deductiblename) {
//		this.deductiblename = deductiblename;
//	}

//	@Column(name = "DEDUCTIBLEAMOUNT", precision = 126, scale = 0)
//	public Double getDeductibleamount() {
//		return this.deductibleamount;
//	}
//
//	public void setDeductibleamount(Double deductibleamount) {
//		this.deductibleamount = deductibleamount;
//	}

//	@Column(name = "ADDLSUMINSUREDNAME")
//	public String getAddlsuminsuredname() {
//		return this.addlsuminsuredname;
//	}
//
//	public void setAddlsuminsuredname(String addlsuminsuredname) {
//		this.addlsuminsuredname = addlsuminsuredname;
//	}
//
//	@Column(name = "ADDLSUMINSUREDAMOUNT", precision = 126, scale = 0)
//	public Double getAddlsuminsuredamount() {
//		return this.addlsuminsuredamount;
//	}
//
//	public void setAddlsuminsuredamount(Double addlsuminsuredamount) {
//		this.addlsuminsuredamount = addlsuminsuredamount;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLENAME")
//	public String getAddldeductiblename() {
//		return this.addldeductiblename;
//	}
//
//	public void setAddldeductiblename(String addldeductiblename) {
//		this.addldeductiblename = addldeductiblename;
//	}
//
//	@Column(name = "ADDLDEDUCTIBLEAMOUNT", precision = 126, scale = 0)
//	public Double getAddldeductibleamount() {
//		return this.addldeductibleamount;
//	}
//
//	public void setAddldeductibleamount(Double addldeductibleamount) {
//		this.addldeductibleamount = addldeductibleamount;
//	}
//
//	@Column(name = "ENDORSEMENTPREMIUM", precision = 126, scale = 0)
//	public Double getEndorsementpremium() {
//		return this.endorsementpremium;
//	}
//
//	public void setEndorsementpremium(Double endorsementpremium) {
//		this.endorsementpremium = endorsementpremium;
//	}
//
//	@Column(name = "EFFECTIVEDATE")
//	public Date getEffectivedate() {
//		return this.effectivedate;
//	}
//
//	public void setEffectivedate(Date effectivedate) {
//		this.effectivedate = effectivedate;
//	}
//
//	@Column(name = "EXPIRYDATE")
//	public Date getExpirydate() {
//		return this.expirydate;
//	}
//
//	public void setExpirydate(Date expirydate) {
//		this.expirydate = expirydate;
//	}
//
//	@Column(name = "ISEXTERNAL", precision = 1, scale = 0)
//	public Boolean getIsexternal() {
//		return this.isexternal;
//	}
//
//	public void setIsexternal(Boolean isexternal) {
//		this.isexternal = isexternal;
//	}
	
/*	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "policycoverage")
	public Set<Policysubcoverage> getPolicysubcoverages() {
		return this.policysubcoverages;
	}

	public void setPolicysubcoverages(Set<Policysubcoverage> policysubcoverages) {
		this.policysubcoverages = policysubcoverages;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "policycoverage")
	public Set<Policycovelement> getPolicycovelements() {
		return this.policycovelements;
	}

	public void setPolicycovelements(Set<Policycovelement> policycovelements) {
		this.policycovelements = policycovelements;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "policycoverage")
	public Set<Policycovvariables> getPolicycovvariableses() {
		return this.policycovvariableses;
	}

	public void setPolicycovvariableses(Set<Policycovvariables> policycovvariableses) {
		this.policycovvariableses = policycovvariableses;
	}*/

}
