package com.fa.component.policy;
// Generated Feb 17, 2017 1:17:05 PM by Hibernate Tools 4.3.5.Final

//import java.io.Serializable;
//import java.math.BigDecimal;
//import java.util.HashSet;
//import java.util.Set;

//import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
//import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
//import javax.persistence.JoinColumn;
//import javax.persistence.OneToMany;
//import javax.persistence.OneToOne;
//import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Privatecaritem generated by hbm2java    MoteritemGenerator
 */
@Entity
@Table(name = "MOTORITEM")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="employee")
public class Privatecaritem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
//    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "partner_sequence")
//	@SequenceGenerator(initialValue=1, allocationSize=1,name = "partner_sequence",sequenceName="partner_sequence21")
/*	@GenericGenerator(name = "custom_MoterItem", strategy = "native")
	@GeneratedValue(generator = "custom_MoterItem")*/
	
	@Id
	@GenericGenerator(name = "generator1", strategy = "foreign", parameters = @Parameter(name = "property", value = "politem"))	
	@GeneratedValue(generator = "generator1")
	@Column(name = "CARID")
	private Long carid;
	private String regdate;
	private String yom;
	private String makecode;
	private String makename;
	private String modelcode;
	private String modelname;
//	private String submodelcode;
//	private String submodelname;
	private Long seatingcapacity;
	private Long enginecapacity;
	private String chassisnumber;
	private String enginenumber;
	private String regnum;
	private String rto;
//	private String regaaddress1;
//	private String regaaddress2;
//	private String regaaddress3;
//	private String regaaddress4;
	private String regcitycode;
	private String regcityname;
	private String regstatecode;
	private String regstatename;
	private long pincode;
	private String zone;
	private String region;
	private String domicile;
	private String fueltype;
//	private String typeofbody;
	private String typeofusage;
	private String colorofvehicle;
//	private Boolean isantitheftfitted;
//	private Boolean isfibretankfitted;
//	private Boolean ispreexistingdamage;
//	private Double listprice;
	private Double idv;
//	private Double idvdeviationpercentage;
	private String mostlydrivenarea;
//	private Boolean isvintage;
//	private Boolean isimported;
//	private Boolean iscustomdutypaid;
//	private String previousinscocode;
//	private String previousinsconame;
//	private String previousinscoaddress;
//	private String previousinspoltype;
//	private String previousinspolno;
//	private Date previouspolexpdate;
//	private Long claimfreeyears;
	private Long ncbpercentage;
//	private Long previousncbpercentage;
//	private Double imposeddedctible;
//	private Double compulsorydeductible;
//	private Double loadingpercentage;
//	private Double discountpercentage;
//	private Boolean isinspectionrequired;
//	private Date inspectiondate;
//	private Boolean ishypothecated;
	private String hypothecationtype;
	private String hypothecatedto;
//	private String additionalcomments;
//	private int isAAIMember=0;
//	private String AAIMembershipNumber;
	private String fgCoverCode;
	private String imtNumbers;
	@Column(name="RISK_Block")
	private int riskBlock=100;
	@Column(name="EML")
	private int EML=100;
	@Column(name="No_of_Driver")
	private int noofDriver=01;
	@Column(name="PRODUCTCODE")
	private String PRODUCTCODE;
	
	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	private Policyitem politem;



	public Long getCarid() {
		return carid;
	}

	public void setCarid(Long carid) {
		this.carid = carid;
	}

	@Column(name = "REGDATE")
	public String getRegdate() {
		return this.regdate;
	}

	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	@Column(name = "MAKECODE")
	public String getMakecode() {
		return this.makecode;
	}

	public void setMakecode(String makecode) {
		this.makecode = makecode;
	}

	@Column(name = "MAKENAME")
	public String getMakename() {
		return this.makename;
	}

	public void setMakename(String makename) {
		this.makename = makename;
	}

	@Column(name = "MODELCODE")
	public String getModelcode() {
		return this.modelcode;
	}

	public void setModelcode(String modelcode) {
		this.modelcode = modelcode;
	}

	@Column(name = "MODELNAME")
	public String getModelname() {
		return this.modelname;
	}

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

//	@Column(name = "SUBMODELCODE")
//	public String getSubmodelcode() {
//		return this.submodelcode;
//	}
//
//	public void setSubmodelcode(String submodelcode) {
//		this.submodelcode = submodelcode;
//	}
//
//	@Column(name = "SUBMODELNAME")
//	public String getSubmodelname() {
//		return this.submodelname;
//	}
//
//	public void setSubmodelname(String submodelname) {
//		this.submodelname = submodelname;
//	}

	@Column(name = "SEATINGCAPACITY", precision = 10, scale = 0)
	public Long getSeatingcapacity() {
		return this.seatingcapacity;
	}

	public void setSeatingcapacity(Long seatingcapacity) {
		this.seatingcapacity = seatingcapacity;
	}

	@Column(name = "ENGINECAPACITY", precision = 10, scale = 0)
	public Long getEnginecapacity() {
		return this.enginecapacity;
	}

	public void setEnginecapacity(Long enginecapacity) {
		this.enginecapacity = enginecapacity;
	}

	@Column(name = "CHASSISNUMBER")
	public String getChassisnumber() {
		return this.chassisnumber;
	}

	public void setChassisnumber(String chassisnumber) {
		this.chassisnumber = chassisnumber;
	}

	@Column(name = "ENGINENUMBER")
	public String getEnginenumber() {
		return this.enginenumber;
	}

	public void setEnginenumber(String enginenumber) {
		this.enginenumber = enginenumber;
	}

	@Column(name = "REGNUM")
	public String getRegnum() {
		return this.regnum;
	}

	public void setRegnum(String regnum) {
		this.regnum = regnum;
	}

	@Column(name = "RTO")
	public String getRto() {
		return this.rto;
	}

	public void setRto(String rto) {
		this.rto = rto;
	}

//	@Column(name = "REGAADDRESS1")
//	public String getRegaaddress1() {
//		return this.regaaddress1;
//	}
//
//	public void setRegaaddress1(String regaaddress1) {
//		this.regaaddress1 = regaaddress1;
//	}
//
//	@Column(name = "REGAADDRESS2")
//	public String getRegaaddress2() {
//		return this.regaaddress2;
//	}
//
//	public void setRegaaddress2(String regaaddress2) {
//		this.regaaddress2 = regaaddress2;
//	}
//
//	@Column(name = "REGAADDRESS3")
//	public String getRegaaddress3() {
//		return this.regaaddress3;
//	}
//
//	public void setRegaaddress3(String regaaddress3) {
//		this.regaaddress3 = regaaddress3;
//	}
//
//	@Column(name = "REGAADDRESS4")
//	public String getRegaaddress4() {
//		return this.regaaddress4;
//	}
//
//	public void setRegaaddress4(String regaaddress4) {
//		this.regaaddress4 = regaaddress4;
//	}

	@Column(name = "REGCITYCODE")
	public String getRegcitycode() {
		return this.regcitycode;
	}

	public void setRegcitycode(String regcitycode) {
		this.regcitycode = regcitycode;
	}

	@Column(name = "REGCITYNAME")
	public String getRegcityname() {
		return this.regcityname;
	}

	public void setRegcityname(String regcityname) {
		this.regcityname = regcityname;
	}

	@Column(name = "REGSTATECODE")
	public String getRegstatecode() {
		return this.regstatecode;
	}

	public void setRegstatecode(String regstatecode) {
		this.regstatecode = regstatecode;
	}

	@Column(name = "REGSTATENAME")
	public String getRegstatename() {
		return this.regstatename;
	}

	public void setRegstatename(String regstatename) {
		this.regstatename = regstatename;
	}

	@Column(name = "ZONE")
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "REGION")
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "DOMICILE")
	public String getDomicile() {
		return this.domicile;
	}

	public void setDomicile(String domicile) {
		this.domicile = domicile;
	}

	@Column(name = "FUELTYPE")
	public String getFueltype() {
		return this.fueltype;
	}

	public void setFueltype(String fueltype) {
		this.fueltype = fueltype;
	}
//
//	@Column(name = "TYPEOFBODY")
//	public String getTypeofbody() {
//		return this.typeofbody;
//	}
//
//	public void setTypeofbody(String typeofbody) {
//		this.typeofbody = typeofbody;
//	}
//
	@Column(name = "TYPEOFUSAGE")
	public String getTypeofusage() {
		return this.typeofusage;
	}

	public void setTypeofusage(String typeofusage) {
		this.typeofusage = typeofusage;
	}

	@Column(name = "COLOROFVEHICLE")
	public String getColorofvehicle() {
		return this.colorofvehicle;
	}

	public void setColorofvehicle(String colorofvehicle) {
		this.colorofvehicle = colorofvehicle;
	}

//	@Column(name = "ISANTITHEFTFITTED", precision = 1, scale = 0)
//	public Boolean getIsantitheftfitted() {
//		return this.isantitheftfitted;
//	}
//
//	public void setIsantitheftfitted(Boolean isantitheftfitted) {
//		this.isantitheftfitted = isantitheftfitted;
//	}
//
//	@Column(name = "ISFIBRETANKFITTED", precision = 1, scale = 0)
//	public Boolean getIsfibretankfitted() {
//		return this.isfibretankfitted;
//	}
//
//	public void setIsfibretankfitted(Boolean isfibretankfitted) {
//		this.isfibretankfitted = isfibretankfitted;
//	}
//
//	@Column(name = "ISPREEXISTINGDAMAGE", precision = 1, scale = 0)
//	public Boolean getIspreexistingdamage() {
//		return this.ispreexistingdamage;
//	}
//
//	public void setIspreexistingdamage(Boolean ispreexistingdamage) {
//		this.ispreexistingdamage = ispreexistingdamage;
//	}
//
//	@Column(name = "LISTPRICE", precision = 126, scale = 0)
//	public Double getListprice() {
//		return this.listprice;
//	}
//
//	public void setListprice(Double listprice) {
//		this.listprice = listprice;
//	}

	@Column(name = "IDV", precision = 126, scale = 0)
	public Double getIdv() {
		return this.idv;
	}

	public void setIdv(Double idv) {
		this.idv = idv;
	}

//	@Column(name = "IDVDEVIATIONPERCENTAGE", precision = 126, scale = 0)
//	public Double getIdvdeviationpercentage() {
//		return this.idvdeviationpercentage;
//	}
//
//	public void setIdvdeviationpercentage(Double idvdeviationpercentage) {
//		this.idvdeviationpercentage = idvdeviationpercentage;
//	}

	@Column(name = "MOSTLYDRIVENAREA")
	public String getMostlydrivenarea() {
		return this.mostlydrivenarea;
	}

	public void setMostlydrivenarea(String mostlydrivenarea) {
		this.mostlydrivenarea = mostlydrivenarea;
	}

//	@Column(name = "ISVINTAGE", precision = 1, scale = 0)
//	public Boolean getIsvintage() {
//		return this.isvintage;
//	}
//
//	public void setIsvintage(Boolean isvintage) {
//		this.isvintage = isvintage;
//	}
//
//	@Column(name = "ISIMPORTED", precision = 1, scale = 0)
//	public Boolean getIsimported() {
//		return this.isimported;
//	}
//
//	public void setIsimported(Boolean isimported) {
//		this.isimported = isimported;
//	}
//
//	@Column(name = "ISCUSTOMDUTYPAID", precision = 1, scale = 0)
//	public Boolean getIscustomdutypaid() {
//		return this.iscustomdutypaid;
//	}
//
//	public void setIscustomdutypaid(Boolean iscustomdutypaid) {
//		this.iscustomdutypaid = iscustomdutypaid;
//	}

//	@Column(name = "PREVIOUSINSCOCODE")
//	public String getPreviousinscocode() {
//		return this.previousinscocode;
//	}
//
//	public void setPreviousinscocode(String previousinscocode) {
//		this.previousinscocode = previousinscocode;
//	}
//
//	@Column(name = "PREVIOUSINSCONAME")
//	public String getPreviousinsconame() {
//		return this.previousinsconame;
//	}
//
//	public void setPreviousinsconame(String previousinsconame) {
//		this.previousinsconame = previousinsconame;
//	}
//
//	@Column(name = "PREVIOUSINSCOADDRESS")
//	public String getPreviousinscoaddress() {
//		return this.previousinscoaddress;
//	}
//
//	public void setPreviousinscoaddress(String previousinscoaddress) {
//		this.previousinscoaddress = previousinscoaddress;
//	}
//
//	@Column(name = "PREVIOUSINSPOLTYPE")
//	public String getPreviousinspoltype() {
//		return this.previousinspoltype;
//	}
//
//	public void setPreviousinspoltype(String previousinspoltype) {
//		this.previousinspoltype = previousinspoltype;
//	}
//
//	@Column(name = "PREVIOUSINSPOLNO")
//	public String getPreviousinspolno() {
//		return this.previousinspolno;
//	}
//
//	public void setPreviousinspolno(String previousinspolno) {
//		this.previousinspolno = previousinspolno;
//	}
//
//	@Column(name = "PREVIOUSPOLEXPDATE")
//	public Date getPreviouspolexpdate() {
//		return this.previouspolexpdate;
//	}
//
//	public void setPreviouspolexpdate(Date previouspolexpdate) {
//		this.previouspolexpdate = previouspolexpdate;
//	}
//
//	@Column(name = "CLAIMFREEYEARS", precision = 10, scale = 0)
//	public Long getClaimfreeyears() {
//		return this.claimfreeyears;
//	}
//
//	public void setClaimfreeyears(Long claimfreeyears) {
//		this.claimfreeyears = claimfreeyears;
//	}
//
//	@Column(name = "PREVIOUSNCBPERCENTAGE", precision = 10, scale = 0)
//	public Long getPreviousncbpercentage() {
//		return this.previousncbpercentage;
//	}
//
//	public void setPreviousncbpercentage(Long previousncbpercentage) {
//		this.previousncbpercentage = previousncbpercentage;
//	}
//
//	@Column(name = "IMPOSEDDEDCTIBLE", precision = 126, scale = 0)
//	public Double getImposeddedctible() {
//		return this.imposeddedctible;
//	}
//
//	public void setImposeddedctible(Double imposeddedctible) {
//		this.imposeddedctible = imposeddedctible;
//	}
//
//	@Column(name = "COMPULSORYDEDUCTIBLE", precision = 126, scale = 0)
//	public Double getCompulsorydeductible() {
//		return this.compulsorydeductible;
//	}
//
//	public void setCompulsorydeductible(Double compulsorydeductible) {
//		this.compulsorydeductible = compulsorydeductible;
//	}
//
//	@Column(name = "LOADINGPERCENTAGE", precision = 126, scale = 0)
//	public Double getLoadingpercentage() {
//		return this.loadingpercentage;
//	}
//
//	public void setLoadingpercentage(Double loadingpercentage) {
//		this.loadingpercentage = loadingpercentage;
//	}
//
//	@Column(name = "DISCOUNTPERCENTAGE", precision = 126, scale = 0)
//	public Double getDiscountpercentage() {
//		return this.discountpercentage;
//	}
//
//	public void setDiscountpercentage(Double discountpercentage) {
//		this.discountpercentage = discountpercentage;
//	}
//
//	@Column(name = "ISINSPECTIONREQUIRED", precision = 1, scale = 0)
//	public Boolean getIsinspectionrequired() {
//		return this.isinspectionrequired;
//	}
//
//	public void setIsinspectionrequired(Boolean isinspectionrequired) {
//		this.isinspectionrequired = isinspectionrequired;
//	}
//
//	@Column(name = "INSPECTIONDATE")
//	public Date getInspectiondate() {
//		return this.inspectiondate;
//	}
//
//	public void setInspectiondate(Date inspectiondate) {
//		this.inspectiondate = inspectiondate;
//	}
//
//	@Column(name = "ISHYPOTHECATED", precision = 1, scale = 0)
//	public Boolean getIshypothecated() {
//		return this.ishypothecated;
//	}
//
//	public void setIshypothecated(Boolean ishypothecated) {
//		this.ishypothecated = ishypothecated;
//	}
//
	
	@Column(name = "HYPOTHECATIONTYPE")
	public String getHypothecationtype() {
		return this.hypothecationtype;
	}

	public void setHypothecationtype(String hypothecationtype) {
		this.hypothecationtype = hypothecationtype;
	}

	@Column(name = "HYPOTHECATEDTO")
	public String getHypothecatedto() {
		return this.hypothecatedto;
	}

	public void setHypothecatedto(String hypothecatedto) {
		this.hypothecatedto = hypothecatedto;
	}

//	@Column(name = "ADDITIONALCOMMENTS")
//	public String getAdditionalcomments() {
//		return this.additionalcomments;
//	}
//
//	public void setAdditionalcomments(String additionalcomments) {
//		this.additionalcomments = additionalcomments;
//	}


//	public Policyitem getPolicyitems() {
//		return this.policyitems;
//	}
//
//	public void setPolicyitems(Policyitem policyitems) {
//		this.policyitems = policyitems;
//	}
	@Column(name = "Yom")
	public String getYom() {
		return yom;
	}

	public void setYom(String yom) {
		this.yom = yom;
	}
	@Column(name = "Pincode")
	public long getPincode() {
		return pincode;
	}

	public void setPincode(long pincode) {
		this.pincode = pincode;
	}
	@Column(name = "Ncbpercentage")
	public Long getNcbpercentage() {
		return ncbpercentage;
	}

	public void setNcbpercentage(Long ncbpercentage) {
		this.ncbpercentage = ncbpercentage;
	}
//	@Column(name = "AAIMember")
//	public int isAAIMember() {
//		return isAAIMember;
//	}
//
//	public void setAAIMember(int isAAIMember) {
//		this.isAAIMember = isAAIMember;
//	}
//	@Column(name = "AAIMembershipNumber")
//	public String getAAIMembershipNumber() {
//		return AAIMembershipNumber;
//	}
//
//	public void setAAIMembershipNumber(String aAIMembershipNumber) {
//		AAIMembershipNumber = aAIMembershipNumber;
//	}
	@Column(name = "FgCoverCode")
	public String getFgCoverCode() {
		return fgCoverCode;
	}

	public void setFgCoverCode(String fgCoverCode) {
		this.fgCoverCode = fgCoverCode;
	}
	@Column(name = "ImtNumbers")
	public String getImtNumbers() {
		return imtNumbers;
	}

	public void setImtNumbers(String imtNumbers) {
		this.imtNumbers = imtNumbers;
	}
	public int getRiskBlock() {
		return riskBlock;
	}

	public void setRiskBlock(int riskBlock) {
		this.riskBlock = riskBlock;
	}

	public int getEML() {
		return EML;
	}

	public void setEML(int eML) {
		EML = eML;
	}

	public int getNoofDriver() {
		return noofDriver;
	}

	public void setNoofDriver(int noofDriver) {
		this.noofDriver = noofDriver;
	}
	public String getPRODUCTCODE() {
		return PRODUCTCODE;
	}

	public void setPRODUCTCODE(String pRODUCTCODE) {
		PRODUCTCODE = pRODUCTCODE;
	}

	

   	public Policyitem getPolitem() {
		return politem;
	}

	public void setPolitem(Policyitem politem) {
		this.politem = politem;
	}
}
