//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 03:22:08 PM IST 
//


package com.firstapex.rs.uw.webservices.policymovements;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.firstapex.rs.uw.webservices.policymovements package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FGUWResponseVO_QNAME = new QName("http://policymovements.webservices.uw.rs.firstapex.com/", "FGUWResponseVO");
    private final static QName _FGUWPolicyVO_QNAME = new QName("http://policymovements.webservices.uw.rs.firstapex.com/", "FGUWPolicyVO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.firstapex.rs.uw.webservices.policymovements
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FguwResponseVO }
     * 
     */
    public FguwResponseVO createFguwResponseVO() {
        return new FguwResponseVO();
    }

    /**
     * Create an instance of {@link FguwPolicyVO }
     * 
     */
    public FguwPolicyVO createFguwPolicyVO() {
        return new FguwPolicyVO();
    }

    /**
     * Create an instance of {@link SettlementVO }
     * 
     */
    public SettlementVO createSettlementVO() {
        return new SettlementVO();
    }

    /**
     * Create an instance of {@link RsVehicleVO }
     * 
     */
    public RsVehicleVO createRsVehicleVO() {
        return new RsVehicleVO();
    }

    /**
     * Create an instance of {@link OldPolicyVO }
     * 
     */
    public OldPolicyVO createOldPolicyVO() {
        return new OldPolicyVO();
    }

    /**
     * Create an instance of {@link CreditCardVO }
     * 
     */
    public CreditCardVO createCreditCardVO() {
        return new CreditCardVO();
    }

    /**
     * Create an instance of {@link ItemSectionVO }
     * 
     */
    public ItemSectionVO createItemSectionVO() {
        return new ItemSectionVO();
    }

    /**
     * Create an instance of {@link ErrorDetailVO }
     * 
     */
    public ErrorDetailVO createErrorDetailVO() {
        return new ErrorDetailVO();
    }

    /**
     * Create an instance of {@link PolicyCoverageVO }
     * 
     */
    public PolicyCoverageVO createPolicyCoverageVO() {
        return new PolicyCoverageVO();
    }

    /**
     * Create an instance of {@link DriverVO }
     * 
     */
    public DriverVO createDriverVO() {
        return new DriverVO();
    }

    /**
     * Create an instance of {@link UserTextVO }
     * 
     */
    public UserTextVO createUserTextVO() {
        return new UserTextVO();
    }

    /**
     * Create an instance of {@link ChequeVO }
     * 
     */
    public ChequeVO createChequeVO() {
        return new ChequeVO();
    }

    /**
     * Create an instance of {@link ClientVO }
     * 
     */
    public ClientVO createClientVO() {
        return new ClientVO();
    }

    /**
     * Create an instance of {@link CoverageVO }
     * 
     */
    public CoverageVO createCoverageVO() {
        return new CoverageVO();
    }

    /**
     * Create an instance of {@link MandateVO }
     * 
     */
    public MandateVO createMandateVO() {
        return new MandateVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FguwResponseVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://policymovements.webservices.uw.rs.firstapex.com/", name = "FGUWResponseVO")
    public JAXBElement<FguwResponseVO> createFGUWResponseVO(FguwResponseVO value) {
        return new JAXBElement<FguwResponseVO>(_FGUWResponseVO_QNAME, FguwResponseVO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FguwPolicyVO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://policymovements.webservices.uw.rs.firstapex.com/", name = "FGUWPolicyVO")
    public JAXBElement<FguwPolicyVO> createFGUWPolicyVO(FguwPolicyVO value) {
        return new JAXBElement<FguwPolicyVO>(_FGUWPolicyVO_QNAME, FguwPolicyVO.class, null, value);
    }

}
