//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 03:22:08 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://policymovements.webservices.uw.rs.firstapex.com/")
package com.firstapex.rs.uw.webservices.policymovements;
